// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS4AeNPx2M_5lQv6WJ6RP85rYSe4Z-J2g',
    appId: '1:853054702494:web:44143d42ab2bb207a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-NFRY5PWFLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2yNxEEZ2QKHWnEuUsxOiDH9Yv74ZHko',
    appId: '1:853054702494:android:97830f6222e3a3c9a30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:c6ff062c460732bfa30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    androidClientId: '853054702494-csod3lklj6hcjr1j310a6c35jtekrt1i.apps.googleusercontent.com',
    iosClientId: '853054702494-5pqg97h0q77qlhc1qetrqjl2a1jbv490.apps.googleusercontent.com',
    iosBundleId: 'com.example.medizaAccountDelete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG7wTqlePvOwOGZ5IhL9YFC2krgYsIoSw',
    appId: '1:853054702494:ios:c6ff062c460732bfa30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    androidClientId: '853054702494-csod3lklj6hcjr1j310a6c35jtekrt1i.apps.googleusercontent.com',
    iosClientId: '853054702494-5pqg97h0q77qlhc1qetrqjl2a1jbv490.apps.googleusercontent.com',
    iosBundleId: 'com.example.medizaAccountDelete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKkyLUyCgBEWOfq0Gs7Yfv5FLWiZgVV1I',
    appId: '1:853054702494:web:d7bd808a222111ada30c8f',
    messagingSenderId: '853054702494',
    projectId: 'docbooking-9ec13',
    authDomain: 'docbooking-9ec13.firebaseapp.com',
    databaseURL: 'https://docbooking-9ec13-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'docbooking-9ec13.appspot.com',
    measurementId: 'G-YFVZPNTC27',
  );
}
